extends Node


const SPEED_BOOST_SPEED = 0.15
const NORMAL_SPEED = 0.38
const TILE_SIZE = 80

enum CHAR_LIST {GODOT, PYTHON, SALAMANDER, CHAMELEON}

enum MAP_LIST {WOODS,STADIUM,OFFICE,CAVE,DISCO,BEACH,RESTAURANT,TOMB}

enum MAP_MODS {CAFFEINATED, TAILVIRUS, EDIBLE_PAPER, LASER, FRUIT_BODY, TETRI_FRUIT}

enum UPGRADE_TYPE {DEFAULT, PASSIVE, BODYMOD, SYNERGY, ACTIVE, SPECIAL}
enum UPGRADE_LIST {	AREA_SIZE_1, AREA_SIZE_2, AREA_SIZE_3,
					FRUIT_MAGNET_1, FRUIT_MAGNET_2, FRUIT_MAGNET_3,
					HYPER_SPEED_1, HYPER_SPEED_2, HYPER_SPEED_3,
					DOUBLE_FRUIT_1, DOUBLE_FRUIT_2, DOUBLE_FRUIT_3,
					EDGE_WRAP_1, EDGE_WRAP_2, 
					FRUIT_RELOCATOR_1, FRUIT_RELOCATOR_2, FRUIT_RELOCATOR_3,
					CROSS_ROAD_1, CROSS_ROAD_2, CROSS_ROAD_3,
					TAIL_CUT,
					KNOT_SLOWMO,
					ITEM_RELOADER,
					IMMUTABLE,
					TIME_STOP_1, TIME_STOP_2, TIME_STOP_3,
					WORMHOLE_1, WORMHOLE_2, WORMHOLE_3,
					CORNER_PHASING,
					MOULTING,
					ANCHOR,
					PIGGY_BANK,
					SALE,
					DIET_1, DIET_2, DIET_3,
					COATING,
					STEEL_HELMET,
					FUEL_1,FUEL_2,FUEL_3,
					RUBBER_BAND,
					SWISS_KNIVE}

var advanced_upgrades: Array[int] = [	UPGRADE_LIST.AREA_SIZE_2, UPGRADE_LIST.AREA_SIZE_3,
										UPGRADE_LIST.FRUIT_MAGNET_2, UPGRADE_LIST.FRUIT_MAGNET_3,
										UPGRADE_LIST.HYPER_SPEED_2, UPGRADE_LIST.HYPER_SPEED_3,
										UPGRADE_LIST.DOUBLE_FRUIT_2, UPGRADE_LIST.DOUBLE_FRUIT_3,
										UPGRADE_LIST.EDGE_WRAP_2,
										UPGRADE_LIST.FRUIT_RELOCATOR_2, UPGRADE_LIST.FRUIT_RELOCATOR_3,
										UPGRADE_LIST.CROSS_ROAD_2, UPGRADE_LIST.CROSS_ROAD_3,
										UPGRADE_LIST.TIME_STOP_2, UPGRADE_LIST.TIME_STOP_3,
										UPGRADE_LIST.WORMHOLE_2, UPGRADE_LIST.WORMHOLE_3,
										UPGRADE_LIST.DIET_2, UPGRADE_LIST.DIET_3,
										UPGRADE_LIST.FUEL_2, UPGRADE_LIST.FUEL_3]

var upgrades_with_advancement: Array[int] = [	UPGRADE_LIST.AREA_SIZE_1, UPGRADE_LIST.AREA_SIZE_2,
												UPGRADE_LIST.FRUIT_MAGNET_1, UPGRADE_LIST.FRUIT_MAGNET_2,
												UPGRADE_LIST.HYPER_SPEED_1, UPGRADE_LIST.HYPER_SPEED_2,
												UPGRADE_LIST.DOUBLE_FRUIT_1, UPGRADE_LIST.DOUBLE_FRUIT_2,
												UPGRADE_LIST.EDGE_WRAP_1,
												UPGRADE_LIST.FRUIT_RELOCATOR_1, UPGRADE_LIST.FRUIT_RELOCATOR_2,
												UPGRADE_LIST.CROSS_ROAD_1, UPGRADE_LIST.CROSS_ROAD_2,
												UPGRADE_LIST.TIME_STOP_1, UPGRADE_LIST.TIME_STOP_2,
												UPGRADE_LIST.WORMHOLE_1, UPGRADE_LIST.WORMHOLE_2,
												UPGRADE_LIST.DIET_1, UPGRADE_LIST.DIET_2,
												UPGRADE_LIST.FUEL_1, UPGRADE_LIST.FUEL_2]


var FRUIT_THRESHOLDS: Array [int] = [7,6,6,5, 8,7,7,6, 9,8,8,7]
const ROUND_TIME_SEC: int = 60
const COLLISION_IFRAMES: int = 4

var node_being_dragged: Node = null

var test_mode = false

func get_upgrade_type(upgrade_id: int):
	
	match upgrade_id:
		UPGRADE_LIST.AREA_SIZE_1, UPGRADE_LIST.AREA_SIZE_2, UPGRADE_LIST.AREA_SIZE_3:
			return UPGRADE_TYPE.DEFAULT
		UPGRADE_LIST.FRUIT_MAGNET_1, UPGRADE_LIST.FRUIT_MAGNET_2, UPGRADE_LIST.FRUIT_MAGNET_3,\
		UPGRADE_LIST.HYPER_SPEED_1, UPGRADE_LIST.HYPER_SPEED_2, UPGRADE_LIST.HYPER_SPEED_3,\
		UPGRADE_LIST.DOUBLE_FRUIT_1, UPGRADE_LIST.DOUBLE_FRUIT_2, UPGRADE_LIST.DOUBLE_FRUIT_3,\
		UPGRADE_LIST.EDGE_WRAP_1, UPGRADE_LIST.EDGE_WRAP_2,\
		UPGRADE_LIST.DIET_1, UPGRADE_LIST.DIET_2, UPGRADE_LIST.DIET_3,\
		UPGRADE_LIST.FUEL_1, UPGRADE_LIST.FUEL_2, UPGRADE_LIST.FUEL_3:
			return UPGRADE_TYPE.PASSIVE
		UPGRADE_LIST.FRUIT_RELOCATOR_1, UPGRADE_LIST.FRUIT_RELOCATOR_2, UPGRADE_LIST.FRUIT_RELOCATOR_3,\
		UPGRADE_LIST.CROSS_ROAD_1, UPGRADE_LIST.CROSS_ROAD_2, UPGRADE_LIST.CROSS_ROAD_3,\
		UPGRADE_LIST.TIME_STOP_1, UPGRADE_LIST.TIME_STOP_2, UPGRADE_LIST.TIME_STOP_3,\
		UPGRADE_LIST.WORMHOLE_1, UPGRADE_LIST.WORMHOLE_2, UPGRADE_LIST.WORMHOLE_3:
			return UPGRADE_TYPE.ACTIVE
		UPGRADE_LIST.TAIL_CUT,\
		UPGRADE_LIST.CORNER_PHASING,\
		UPGRADE_LIST.COATING,\
		UPGRADE_LIST.STEEL_HELMET,\
		UPGRADE_LIST.RUBBER_BAND:
			return UPGRADE_TYPE.BODYMOD
		UPGRADE_LIST.KNOT_SLOWMO,\
		UPGRADE_LIST.ITEM_RELOADER,\
		UPGRADE_LIST.PIGGY_BANK,\
		UPGRADE_LIST.SWISS_KNIVE,\
		UPGRADE_LIST.SALE:
			return UPGRADE_TYPE.SYNERGY
		UPGRADE_LIST.IMMUTABLE,\
		UPGRADE_LIST.MOULTING,\
		UPGRADE_LIST.ANCHOR:
			return UPGRADE_TYPE.SPECIAL
		_:
			print_debug("notype has been found for this upgrade: " + str(upgrade_id))

func _ready() -> void:
	if test_mode:
		FRUIT_THRESHOLDS = [0,0,0,0, 0,0,0,0, 0,0,0,0]
