extends Node


const SPEED_BOOST_SPEED = 0.15
const NORMAL_SPEED = 0.38
const TILE_SIZE = 80

enum UPGRADE_TYPE {DEFAULT, PASSIVE, BODYMOD, SYNERGY, ACTIVE, SPECIAL}
enum UPGRADE_LIST {	AREA_SIZE_1, AREA_SIZE_2, AREA_SIZE_3,
					FRUIT_MAGNET_1, FRUIT_MAGNET_2, FRUIT_MAGNET_3,
					HYPER_SPEED_1, HYPER_SPEED_2, HYPER_SPEED_3,
					DOUBLE_FRUIT_1, DOUBLE_FRUIT_2, DOUBLE_FRUIT_3,
					EDGE_WRAP_1, EDGE_WRAP_2, 
					FRUIT_RELOCATOR_1, FRUIT_RELOCATOR_2, FRUIT_RELOCATOR_3,
					CROSS_ROAD_1, CROSS_ROAD_2, CROSS_ROAD_3,
					TAIL_CUT,
					KNOT_ATTRACTOR,
					ITEM_RELOADER,
					IMMUTABLE,
					TIME_STOP_1, TIME_STOP_2, TIME_STOP_3,
					WORMHOLE_1, WORMHOLE_2, WORMHOLE_3,
					CORNER_PHASING,
					MOULTING}

var advanced_upgrades: Array[int] = [	UPGRADE_LIST.AREA_SIZE_2, UPGRADE_LIST.AREA_SIZE_3,
										UPGRADE_LIST.FRUIT_MAGNET_2, UPGRADE_LIST.FRUIT_MAGNET_3,
										UPGRADE_LIST.HYPER_SPEED_2, UPGRADE_LIST.HYPER_SPEED_3,
										UPGRADE_LIST.DOUBLE_FRUIT_2, UPGRADE_LIST.DOUBLE_FRUIT_3,
										UPGRADE_LIST.EDGE_WRAP_2,
										UPGRADE_LIST.FRUIT_RELOCATOR_2, UPGRADE_LIST.FRUIT_RELOCATOR_3,
										UPGRADE_LIST.CROSS_ROAD_2, UPGRADE_LIST.CROSS_ROAD_3,
										UPGRADE_LIST.TIME_STOP_2, UPGRADE_LIST.TIME_STOP_3,
										UPGRADE_LIST.WORMHOLE_2, UPGRADE_LIST.WORMHOLE_3]

var upgrades_with_advancement: Array[int] = [	UPGRADE_LIST.AREA_SIZE_1, UPGRADE_LIST.AREA_SIZE_2,
												UPGRADE_LIST.FRUIT_MAGNET_1, UPGRADE_LIST.FRUIT_MAGNET_2,
												UPGRADE_LIST.HYPER_SPEED_1, UPGRADE_LIST.HYPER_SPEED_2,
												UPGRADE_LIST.DOUBLE_FRUIT_1, UPGRADE_LIST.DOUBLE_FRUIT_2,
												UPGRADE_LIST.EDGE_WRAP_1,
												UPGRADE_LIST.FRUIT_RELOCATOR_1, UPGRADE_LIST.FRUIT_RELOCATOR_2,
												UPGRADE_LIST.CROSS_ROAD_1, UPGRADE_LIST.CROSS_ROAD_2,
												UPGRADE_LIST.TIME_STOP_1, UPGRADE_LIST.TIME_STOP_2,
												UPGRADE_LIST.WORMHOLE_1, UPGRADE_LIST.WORMHOLE_2]
 

					
var FRUIT_THRESHOLDS: Array [int] = [13,12,11,10, 18,17,16,15, 23,22,21,20]
const ROUND_TIME_SEC: int = 8
const COLLISION_IFRAMES: int = 3

var node_being_dragged: Node = null

var test_mode = true

func get_upgrade_type(upgrade_id: int):
	
	match upgrade_id:
		UPGRADE_LIST.AREA_SIZE_1, UPGRADE_LIST.AREA_SIZE_2, UPGRADE_LIST.AREA_SIZE_3:
			return UPGRADE_TYPE.DEFAULT
		UPGRADE_LIST.FRUIT_MAGNET_1, UPGRADE_LIST.FRUIT_MAGNET_2, UPGRADE_LIST.FRUIT_MAGNET_3,\
		UPGRADE_LIST.HYPER_SPEED_1, UPGRADE_LIST.HYPER_SPEED_2, UPGRADE_LIST.HYPER_SPEED_3,\
		UPGRADE_LIST.DOUBLE_FRUIT_1, UPGRADE_LIST.DOUBLE_FRUIT_2, UPGRADE_LIST.DOUBLE_FRUIT_3,\
		UPGRADE_LIST.EDGE_WRAP_1, UPGRADE_LIST.EDGE_WRAP_2:
			return UPGRADE_TYPE.PASSIVE
		UPGRADE_LIST.FRUIT_RELOCATOR_1, UPGRADE_LIST.FRUIT_RELOCATOR_2, UPGRADE_LIST.FRUIT_RELOCATOR_3,\
		UPGRADE_LIST.CROSS_ROAD_1, UPGRADE_LIST.CROSS_ROAD_2, UPGRADE_LIST.CROSS_ROAD_3,\
		UPGRADE_LIST.TIME_STOP_1, UPGRADE_LIST.TIME_STOP_2, UPGRADE_LIST.TIME_STOP_3,\
		UPGRADE_LIST.WORMHOLE_1, UPGRADE_LIST.WORMHOLE_2, UPGRADE_LIST.WORMHOLE_3:
			return UPGRADE_TYPE.ACTIVE
		UPGRADE_LIST.TAIL_CUT,\
		UPGRADE_LIST.CORNER_PHASING:
			return UPGRADE_TYPE.BODYMOD
		UPGRADE_LIST.KNOT_ATTRACTOR, UPGRADE_LIST.ITEM_RELOADER:
			return UPGRADE_TYPE.SYNERGY
		UPGRADE_LIST.IMMUTABLE,\
		UPGRADE_LIST.MOULTING:
			return UPGRADE_TYPE.SPECIAL
		_:
			print_debug("notype has been found for this upgrade: " + str(upgrade_id))

func _ready() -> void:
	if test_mode:
		FRUIT_THRESHOLDS = [0,0,0,0, 25,25,25,25, 30,30,30,30]
